### ISSUE TITLE
Add support for soft signals, e.g. calc

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/pvi#119]
And find them during convert

**Comment by GDYendell** [comment]
@coretl @gilesknap do you think we should include all calc records in convert? I think some of them might just be for internal database logic and shouldn't be shown on the UI. Similarly, I think calcouts will mainly be for database logic, but possibly some would be useful on the UI.

Any thoughts on some heuristics we could use to decide what to include? Or, should we stick to having to manually add calc and calcout to the yaml manually?

**Comment by coretl** [comment]
I think we should use a manual list, but did we talk about capturing all the pvi convert in a yaml file somewhere so @gilesknap can run pvi convert with the same options many times until the yaml becomes a source file?

**Comment by GDYendell** [comment]
OK well I have just opened #126 to allow reconvert. So, if there are device.yamls with manually added calc records, reconvert can be run on them to add new PVs without losing the manually added ones.
