### ISSUE TITLE
SignalX components in BOB files have no actions and wrong PV

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [epics-containers/pvi#20]
Creating a SignalX component with a syntax like this:
```
record_name = "SOME:RECORD"
SignalX(record_name, record_name, value=1)
```

and passing it through the DLSFormatter to make a `.bob` file creates an `ActionButton` in the output. However, the PV associated with it does NOT have the prefix that is provided to the formatter, unlike other components. It also has no Actions associated with it, implying it will not send the given value when pressed.

**Comment by GDYendell** [comment]
Fixed in #32
