### ISSUE TITLE
Current schema files are incorrect for EPICS 3.14.12.7

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [epics-containers/pvi#21]
Currently we use the latest version of epicscorelibs, which is for version 7 of EPICS. This is what is used to generate the schema file `/schemas/pvi.producer.schema.json`. As it's based on EPICS 7, there is a high chance that there are items in this schema that are invalid for Diamond's standard EPICS version of 3.14.12.7. 

This issue came to light when, as part of PR #19 , I updated to use epicscorelibs 7.0.7.99.0.0. This introduced new values for certain record's SIMM fields, which are invalid in R 3.14.12.7.

We should provide some mechanism for users to specify an EPICS version, and we should then use a schema file from that same version to validate their data.

**Comment by GDYendell** [comment]
Producer has been removed so this is a non-issue.
