### ISSUE TITLE
Allow formatter to return text rather than write into path

### ISSUE THREAD

**Issue by coretl** [epics-containers/pvi#23]
It would definitely be neater if we can get an API change, or a new API, for PVI to just return us the text content of the .bob file. @coretl @GDYendell any thoughts on this?

_Originally posted by @AlexanderWells-diamond in https://github.com/PandABlocks/PandABlocks-client/pull/43#discussion_r1081487037_

**Comment by GDYendell** [comment]
Seems reasonable. You would just want the raw text as it is just before writing to file, but returned directly from the API call? Or would it be in some structure format, e.g. the [ElementTree](https://github.com/epics-containers/pvi/blob/master/src/pvi/_format/dls.py#L241)?

**Comment by GDYendell** [comment]
I think this is not needed now because the code referenced in PandA has been removed. Is this correct @coretl ?

**Comment by coretl** [comment]
yes, we now write to file so this is no longer needed
