### ISSUE TITLE
Add `choices` to `ComboBox` and make phoebus support it

### ISSUE THREAD

**Issue by coretl** [epics-containers/pvi#25]
Extend https://github.com/epics-containers/pvi/blob/master/src/pvi/device.py#L114 to have `choices` like `BitField` has `labels`. If specified, the PV is assumed to be a string providing the current value, but the enum `choices` should be the ones in the `ComboBox` pvi structure rather than trying to get them from the PV metadata. 

Add support for adding these to bob files. The `combo` widget supports this, you have to set:
```xml
    <items>
      <item>item 0</item>
      <item>Item 1</item>
    </items>
    <items_from_pv>false</items_from_pv>
```

**Comment by GDYendell** [comment]
e.g. PV with 120 enum entries, populate combo box entries with given choices instead of reading from mbbi fields, which are limited to 16 (?).

**Comment by GDYendell** [comment]
Added in #22
