### ISSUE TITLE
SignalRW widget widths are split too early

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/pvi#41]
The widget width for a `SignalRW` is split before the decision as to whether to display a read widget or not. This means it can display just a write widget, but at half the requested width (plus padding).

This needs discussion of what the default behaviour should be when a `SignalRW` is not given a `read_widget`. The help suggests it will use `widget`, but this doesn't make sense e.g. if `widget` is a `TextWrite`. Currently it just doesn't add a read widget.

**Comment by coretl** [comment]
I think it should:

```python
if sig.read_pv:
    make_single_width(sig.widget, sig.pv)
    read_widget = sig.read_widget if sig.read_widget else sig.widget
    make_single_width(read_widget, sig.read_pv)
else:
    make_double_width(sig.widget, sig.pv)
```

**Comment by GDYendell** [comment]
So in this case 
```
read_widget = sig.read_widget if sig.read_widget else sig.widget
```

it would use a `TextWrite` widget for the read PV. Is that not bad? I think maybe it should be hardcoded to `TextRead`, or maybe have a function to map write widgets to an equivalent read widget if there is one.

**Comment by coretl** [comment]
Yeah, let's hardcode to `TextRead`

**Comment by evalott100** [comment]
Fixed in https://github.com/epics-containers/pvi/pull/57
