### ISSUE TITLE
Improve Device validation error messages

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/pvi#99]
Currently when validation fails for a `Device` with parents it is not clear which yaml file the failure is in.

We could catch the error in `Device.deserialize` and add some context, but this would be too late to tell which yaml file the problem is in because it is all loaded into one dictionary at this point. Perhaps `Device.deserialize_parents` should validate each as it is loaded and fail at that point.

**Comment by gilesknap** [comment]
I approve this message.
